base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login$', views.login_start, name='login_start'),
    url(r'^login_process$', views.login_process, name='login_process'),
    url(r'^logout/(?P<court_id>[0-9]+)/?$', views.logout, name='logout'),
    url(r'^history/(?P<court_id>[0-9]+)/(?P<page_id>[0-9]+)/?$', views.history, name='history'),
    url(r'^statistics/(?P<court_id>[0-9]+)/?$', views.statistics, name='stats'),

    url(r'^reserve_ticket$', views.reserve, name='reserve'),
    url(r'^process_ticket/(?P<court_id>[0-9]+)/?$', views.process_ticket, name='process_ticket'),

    url(r'^(?P<court_id>[0-9]+)/?$', views.court, name='court'),
    url(r'^.*$', views.index, name="home"),
]

justcount/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('base.urls', namespace="base"))
]

base/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta

# Create your models here.

class Court(models.Model):
    name = models.CharField(max_length=500)
    key = models.CharField(max_length=100, default="This Is The Default Password 123")

    def __str__(self):
        return self.name

def now_plus_thirty():
    return timezone.now() + timedelta(days=30)

class Ticket(models.Model):
    name = models.CharField(max_length=40)
    request_stamp = models.DateTimeField(default=timezone.now)
    served_stamp = models.DateTimeField(default=now_plus_thirty)
    message = models.TextField(max_length=5000)
    email = models.EmailField()
    court = models.ForeignKey('Court')

    def __str__(self):
        return "Name: {}\nEmail: {}\nRequested: {}\nServed: {}\nMessage: {}\nCourt: {}".format(self.name,self.email,self.request_stamp,self.served_stamp,self.message,self.court)

base/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Court, Ticket
from django.contrib import messages
from django.core.mail import send_mail
from django.utils import timezone as datetime
from datetime import timedelta

# Create your views here.

def index(request):
    court_list = Court.objects.all()
    context = {'court_list': court_list}
    return render(request, 'base/index.html', context)

def court(request, court_id):
    court = get_object_or_404(Court, pk=court_id)
    now=datetime.now()
    ticket_list = Ticket.objects.filter(court=court, served_stamp__gt=now).values_list('id', flat=True)
    if 'court_agent_' + str(court_id) in request.session:
        agent_data = Ticket.objects.filter(court=court, served_stamp__gt=now)
        return render(request, 'base/court.html', {'court': court, 'ticket_list': ticket_list, 'agent_data': agent_data, 'logged_in': True})
    else:
        return render(request, 'base/court.html', {'court': court, 'ticket_list': ticket_list})

def history(request, court_id, page_id):
    page_id = int(page_id)
    if 'court_agent_' + str(court_id) in request.session:
        tickets_per_page = 5
        if page_id == None:
            page_id = 0
        start_ticket = page_id
        end_ticket = start_ticket + tickets_per_page;
        court = get_object_or_404(Court, pk=court_id)
        now=datetime.now()
        tickets = Ticket.objects.filter(court=court, served_stamp__lt=now).order_by('id')
        if len(tickets) < start_ticket:
            messages.error(request, "No tickets on that page.")
            return render(request, 'base/history.html', {'court': court, 'next_page': start_ticket, 'prev_page': max(0,start_ticket - tickets_per_page), 'logged_in': True})
        else:
            return render(request, 'base/history.html', {'court': court, 'history_data': tickets[start_ticket:min(end_ticket, len(tickets))], 'next_page': start_ticket + tickets_per_page, 'prev_page': max(0,start_ticket - tickets_per_page), 'logged_in': True})
    else:
        messages.error(request, "You must be logged in to view history.")
        return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))

def statistics(request, court_id):
    court = get_object_or_404(Court, pk=court_id)
    now=datetime.now()
    tickets = Ticket.objects.filter(court=court, served_stamp__lt=now).order_by('id')
    avg_time = round(sum(((i.served_stamp - i.request_stamp).seconds/60 for i in tickets))/len(tickets), 2)
    total_served = len(tickets);
    total_served_year = len(tickets.filter(served_stamp__gt=(now-timedelta(days=365))))
    total_served_month = len(tickets.filter(served_stamp__gt=(now-timedelta(days=30))))
    total_served_day = len(tickets.filter(served_stamp__gt=(now-timedelta(days=1))))

    logged_in = False
    if 'court_agent_' + str(court_id) in request.session:
        logged_in = True
    return render(request, 'base/statistics.html', {'court': court, 'avg_time': avg_time, 'total_served': total_served, 'total_served_year': total_served_year, 'total_served_month': total_served_month, 'total_served_day': total_served_day, 'logged_in': logged_in})

def reserve(request):
    name = request.POST['name']
    email = request.POST['email']
    message = request.POST['message']
    court_id = request.POST['court_id']

    if not name or not email:
        messages.error(request, "Please enter all fields")
        return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))
    try:
        t = Ticket()
        t.name = name
        t.message = message
        t.email = email
        t.court = Court.objects.get(id=court_id)

        now=datetime.now()
        tickets = Ticket.objects.filter(court=t.court, served_stamp__lt=now).order_by('id')
        queued_tickets = len(Ticket.objects.filter(court=t.court, served_stamp__gt=now))
        avg_time = int(sum(((i.served_stamp - i.request_stamp).seconds/60 for i in tickets))/len(tickets) * queued_tickets)

        send_mail("Ticket Reserved!", "Your ticket number is {}.\nYour estimated wait time is {} minutes.".format(len(Ticket.objects.all()) + 1, avg_time), "justcountbot@gmail.com", [email], fail_silently=False)

        t.save()

        messages.success(request, "Your ticket has been submitted! Your ticket number is {}".format(t.id))
    except:
        messages.error(request, "Invalid data. Check your email address.")
    return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))

def process_ticket(request, court_id):
    if 'court_agent_' + str(court_id) in request.session:
        court = get_object_or_404(Court, pk=court_id)
        now=datetime.now()
        tickets = Ticket.objects.filter(court=court, served_stamp__gt=now).order_by('id')
        if tickets:
            next_ticket = tickets[0]
            next_ticket.served_stamp = now
            next_ticket.save()
            messages.success(request, "Ticket #{} has now been served!".format(next_ticket.id))
        else:
            messages.error(request, "No tickets left to serve.")
    else:
        messages.error(request, "You must be logged in to process a ticket.")
    return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))


def login_start(request):
    court_list = Court.objects.all()
    context = {'court_list': court_list}
    return render(request, 'base/login.html', context)

def login_process(request):
    try:
        court_id = request.POST['court_id']
    except:
        messages.error(request, "Please select your court.")
        return HttpResponseRedirect(reverse('base:login_start'))

    key = request.POST['key']
    actual_key = Court.objects.get(id=court_id).key
    if key == actual_key:
        request.session['court_agent_' + str(court_id)] = True
        messages.success(request, "You've been logged in!")
        return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))

    messages.error(request, "Login Failure")
    return HttpResponseRedirect(reverse('base:login_start'))

def logout(request, court_id):
    request.session.flush()
    messages.success(request, "You've been logged out!")
    return HttpResponseRedirect(reverse('base:court', kwargs={'court_id':court_id}))

base/templates/base/court.html
{% include "base/head.html" %}



<div class="court-center">

    {% include "base/nav.html" %}

    <script>
        $('.ticketlink').addClass('greenlink');
    </script>

    <div class="court-name">{{court.name}} Tickets</div>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
            <br /> {% endfor %}
    </div>
    {% endif %}

    {% if not logged_in %}
    <div class="header">Request a ticket</div>
    <form class="reserve-form bottom-padding" action="{% url 'base:reserve' %}" method="post">
        {% csrf_token %}

        <input name="court_id" type="hidden" class="court_id form-control" value="{{court.id}}"></input>
        <input name="name" type="text" class="form-control" placeholder="Your full name" />
        <input name="email" type="text" class="form-control" placeholder="Your email" />
        <textarea name="message" class="form-control" rows="3" maxlength="5000" placeholder="Your concern"></textarea>
        <input type="submit" class="btn btn-default top-margin" value="Submit Request" />

    </form>
    {% endif %}

    <div class="header">Enqueued Tickets</div>


    {% if logged_in %}

        {% if agent_data %}
            <div class="section">
                <a href="{% url 'base:process_ticket' court.id%}">
                    <button type="button" class="btn btn-default">Process Next Ticket</button>
                </a>
            </div>
            {% for ticket in agent_data %}
            <pre class="ticket margin-top">{{ticket}}</pre>
            {% endfor %}
        {% else %}
            <pre class="margin-top">No tickets are enqueued.</pre>
        {% endif %}

    {% else %}

        {% if ticket_list %}
            {% for ticket in ticket_list %}
                <pre class="ticket margin-top">{{ ticket }}</pre>
            {% endfor %}
        {% else %}

        <pre class="margin-top">No tickets are enqueued.</pre>
    {% endif %} {% endif %}

</div>

base/templates/base/head.html
<!DOCTYPE html>
<head>
<title>Just Count</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'base/main.css' %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Lato:100,300,900,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'base/animate.css' %}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="{% static 'base/main.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

base/templates/base/history.html
{% include "base/head.html" %}

<div class="history">

    <div class="history-center">

        {% include "base/nav.html" %}

        <script>
            $('.historylink').addClass('greenlink');
        </script>

        <div class="court-name">{{court.name}} Ticket History</div>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <a{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</a>
                <br /> {% endfor %}
        </div>
        <br /> {% endif %} {% if logged_in %}

        <div class="section">
            <a href="{% url 'base:history' court.id prev_page %}">
                <button type="button" class="btn btn-default">Previous</button>
            </a>
            <a href="{% url 'base:history' court.id next_page %}">
                <button type="button" class="btn btn-default">Next</button>
            </a>
        </div>

        {% if history_data %} {% for ticket in history_data %}
        <pre class="ticket margin-top">{{ticket}}</pre>
        {% endfor %} {% else %}
        <pre class="margin-top">No tickets to show.</pre>
        {% endif %} {% else %}
        <pre class="margin-top">You must be logged in to view History.</pre>
        {% endif %}

    </div>

</div>

base/templates/base/index.html
{% include "base/head.html" %}

{% if court_list %}

<div class="home-center">
    <div class="home-title animated slideInDown">Just Count</div>
    <div class="home-sub animated slideInUp">
        A Simple Service Tracker
        <br> For the U.S. Department of Justice
        <br>
    </div>

    <div class="selection animated slideInUp">
        <select name="court_id" class="form-control court-list" onchange="location = this.options[this.selectedIndex].value;">
            <option disabled selected>Select Court</option>

            {% for court in court_list %}
                <option value="{{court.id}}" value="{% url 'base:court' court.id %}">{{ court.name }}</option>
            {% endfor %}
        </select>
    </div>


{% else %}

    <p>No courts are available.</p>

{% endif %}

base/templates/base/login.html
{% include "base/head.html" %}

<div class="login-center">

    <a href="{% url 'base:home' %}">Home</a>
    <div class="court-name">Court Login</div>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}


    {% if court_list %}

        <form action="{% url 'base:login_process' %}" method="post" class="bottom-margin">
            {% csrf_token %}

            <select name="court_id" class="form-control">
                <option disabled selected>Select Court</option>

                {% for court in court_list %}
                <option value="{{court.id}}">{{ court.name }}</li>
                    {% endfor %}
            </select>

            <input name="key" type="password" class="form-control" placeholder="Key" />
            <input type="submit" class="btn btn-default top-margin" value="Login" />
        </form>

    {% else %}

        <p>No courts are available.</p>

    {% endif %}

</div>

base/templates/base/nav.html
<a href="{% url 'base:home' %}" class="homelink">Home</a>
<a href="{% url 'base:court' court.id %}" class="ticketlink">Tickets</a>
<a href="{% url 'base:stats' court.id%}" class="statlink">Statistics</a>

{% if logged_in %}
    <a href="{% url 'base:history' court.id 0%}" class="historylink">History</a>
    <a href="{% url 'base:logout' court.id %}" class="logoutlink">Log Out</a>
{% endif %}

base/templates/base/statistics.html
{% include "base/head.html" %}

<div class="stat-center">

    {% include "base/nav.html" %}

    <script>
        $('.statlink').addClass('greenlink');
    </script>

    <div class="court-name">{{court.name}} Statistics</div>


    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <a{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</a>
            <br /> {% endfor %}
    </div>
    {% endif %}

    <div class="stat-box">
        <div class="stat">
            <span class="green">{{avg_time}}</span>
             minutes per ticket
        </div>

        <div class="stat">
            <span class="green">{{total_served_day}}</span>
            tickets served in the last 24 hours
        </div>

        <div class="stat">
            <span class="green">{{total_served_month}}</span>
            tickets served last month
        </div>

        <div class="stat">
            <span class="green">{{total_served_year}}</span>
            tickets served last year
        </div>

        <div class="stat">
            <span class="green">{{total_served}}</span>
            tickets served all time
        </div>
    </div>


</div>